### ISSUE TITLE
Using a custom controller

### ISSUE THREAD

**Issue by theofidry** [dunglas/DunglasJsonLdApiBundle#15]
Overriding a method of the controller is easy as it's just requires to extend the `ResourceController`. However in the case we wish to add a new action to the controller, for example `countAction`, to get the API endpoint `GET /collection/count`; It would be possible to add our route manually in our routing file, but then our rout would not "inherit" the prefixes that it would get if it were declared directly in the parent controller `ResourceController`. Is there a way to that in a more elegant manner?

**Comment by dunglas** [comment]
As done for many other bundles, defining a prefix in your custom routing (trough annotations, XML or YAML) works and doesn't conflict with the bundle own routing system (I've already done that).

A cleaner but untested way should be to use the bundle "operation" definitions to map the custom route:
1. Create your custom action in your controller
2. Register the operation like the following:

```yaml
services:
    my_dummy_resource:
        class:     Dunglas\JsonLdApiBundle\JsonLd\Resource
        arguments:
          - Dunglas\JsonLdApiBundle\Tests\Behat\TestBundle\Entity\Dummy
          - []
          - []
          - []
          - ~
          - ~
          - ~ # To customize collection operations it's here
          - # And here for item operations
            - { "hydra:method" => "GET" } # We add back default operations and let them be populated by the bundle
            - { "hydra:method" => "PUT" } # Same here
            - { "hydra:method" => "DELETE" } # Same here
            - { "hydra:title": "My custom operation", "!controller": "MyController:myAction", "!route_name": "my_route_name", "!route_path": "{id}/custom", "hydra:method" => "GET" } # Here is the custom operation
        tags:
          - { name: json-ld.resource }
```

Let me know if it works.
