### ISSUE TITLE
Nitpicking - style

### ISSUE THREAD

**Issue by theofidry** [dunglas/DunglasJsonLdApiBundle#33]
In extract of Yaml code (ex: [disabling-operations](https://github.com/dunglas/DunglasJsonLdApiBundle/tree/refactoring#disabling-operations)), you indent the code as the following:

```yml
services:
    resource.product.collection_operation.get:
        class:                                 "Dunglas\JsonLdApiBundle\Api\Operation\Operation"
        public:                                false
        factory:                               [ "@api.operation_factory", "createItemOperation" ]
        arguments:                             [ "@resource.product", "GET" ]

    resource.product:
        parent:                                "api.resource"
        arguments:                             [ "AppBundle\Entity\Product" ]
            -                                  [ "addCollectionOperation", [ "@resource.product.collection_operation.get" ] ]
        tags:                                  [ { name: "api.resource" } ]
```

While the result is clean and pretty, the space between the key and the value is far too big and result in two things:
* If you have a column not wide enough (on a mobile or simply in our case the width of the readme), you have to scroll to see the actual value.
* If you are a little bit dyslexic, it is completely unreadable.

Maybe keeping the indentation as follow would be a better although less pretty (at least IMO):

```yml
services:
    resource.product.collection_operation.get:
        class:     "Dunglas\JsonLdApiBundle\Api\Operation\Operation"
        public:    false
        factory:   [ "@api.operation_factory", "createItemOperation" ]
        arguments: [ "@resource.product", "GET" ]

    resource.product:
        parent:    "api.resource"
        arguments: [ "AppBundle\Entity\Product" ]
            -      [ "addCollectionOperation", [ "@resource.product.collection_operation.get" ] ]
        tags:      [ { name: "api.resource" } ]
```

And maybe remove unnecessary `"`:

```yml
services:
    resource.product.collection_operation.get:
        class:     Dunglas\JsonLdApiBundle\Api\Operation\Operation
        public:    false
        factory:   [ @api.operation_factory, createItemOperation ]
        arguments: [ @resource.product, GET ]

    resource.product:
        parent:    api.resource
        arguments: [ AppBundle\Entity\Product ]
            -      [ addCollectionOperation, [ @resource.product.collection_operation.get ] ]
        tags:      [ { name: api.resource } ]
```

Or does it causes any error?
